# B. DISKRITISASI
>*Diskritisasi adalah kegiatan yang dilakukan untuk mengubah niai data numerik menjadi kategorial*

## Tugas 2

## Mencari Data Kategorikal 

1.   Lakukan proses diskritisasi dengan equal width dan equal frequency
2.   Lakukan proses diskritisasi dengan basis entropy

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import statistics as st
import numpy as np

## Data

In [ ]:
data2 ='https://raw.githubusercontent.com/SanS2A/dataset/main/IRIS.csv'

In [ ]:
df2 = pd.read_csv(data2)

In [ ]:
df2

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
SepalLength = df2['sepal_length']
SepalWidth = df2['sepal_width']
PetalLength = df2['petal_length']
PetalWith = df2['petal_width']

In [ ]:
labels = ['kecil', 'sedang', 'besar']

## 1. Lakukan proses diskritisasi dengan equal width dan equal frequency

### Diskritisasi adalah

### Min, Max

In [ ]:
SepalLength

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

In [ ]:
SepalWidth

0      3.5
1      3.0
2      3.2
3      3.1
4      3.6
      ...
145    3.0
146    2.5
147    3.0
148    3.4
149    3.0
Name: sepal_width, Length: 150, dtype: float64

In [ ]:
PetalLength

0      1.4
1      1.4
2      1.3
3      1.5
4      1.4
      ...
145    5.2
146    5.0
147    5.2
148    5.4
149    5.1
Name: petal_length, Length: 150, dtype: float64

In [ ]:
labels1 = ['kecil', 'sedang', 'besar']
# LabelledBinning1 = pd.qcut(df2['petal_length'],len(labels1), True, labels1).value_counts()

In [ ]:
MinMaxSepalLength = [np.min(df2['sepal_length']),np.max(df2['sepal_length'])]
MinMaxSepalWidth = [np.min(df2['sepal_width']),np.max(df2['sepal_width'])]
MinMaxPetalLength = [np.min(df2['petal_length']),np.max(df2['petal_length'])]
MinMaxPetalWith = [np.min(df2['petal_width']),np.max(df2['petal_width'])]

In [ ]:
PetalWith

0      0.2
1      0.2
2      0.2
3      0.2
4      0.2
      ...
145    2.3
146    1.9
147    2.0
148    2.3
149    1.8
Name: petal_width, Length: 150, dtype: float64

### Data Equal Width

#### Data Sepal Length

In [ ]:
Sepal_Length_Binning = pd.cut(df2['sepal_length'],len(labels), True, labels)
Labelled_Sepal_Length_Binning = Sepal_Length_Binning.value_counts()
NoLabelled_Sepal_Length_Binning = pd.cut(df2['sepal_length'],len(labels)).value_counts()
# IntervalBinning = pd.cut()

In [ ]:
Labelled_Sepal_Length_Binning

sedang    71
kecil     59
besar     20
Name: sepal_length, dtype: int64

In [ ]:
pd.concat((df2['sepal_length'],Sepal_Length_Binning),axis=1).head(15)

   sepal_length sepal_length
0           5.1        kecil
1           4.9        kecil
2           4.7        kecil
3           4.6        kecil
4           5.0        kecil
5           5.4        kecil
6           4.6        kecil
7           5.0        kecil
8           4.4        kecil
9           4.9        kecil
10          5.4        kecil
11          4.8        kecil
12          4.8        kecil
13          4.3        kecil
14          5.8       sedang

#### Data Sepal Width

In [ ]:
Sepal_Width_Binning = pd.cut(df2['sepal_width'],len(labels), True, labels)
Labelled_Sepal_Width_Binning = Sepal_Width_Binning.value_counts()
NoLabelled_Sepal_Width_Binning = pd.cut(df2['sepal_width'],len(labels)).value_counts()
# IntervalBinning = pd.cut()

In [ ]:
Labelled_Sepal_Width_Binning

sedang    88
kecil     47
besar     15
Name: sepal_width, dtype: int64

In [ ]:
NoLabelled_Sepal_Width_Binning

(2.8, 3.6]      88
(1.998, 2.8]    47
(3.6, 4.4]      15
Name: sepal_width, dtype: int64

In [ ]:
pd.concat((df2['sepal_width'],Sepal_Width_Binning),axis=1).head(15)

   sepal_width sepal_width
0          3.5      sedang
1          3.0      sedang
2          3.2      sedang
3          3.1      sedang
4          3.6      sedang
5          3.9       besar
6          3.4      sedang
7          3.4      sedang
8          2.9      sedang
9          3.1      sedang
10         3.7       besar
11         3.4      sedang
12         3.0      sedang
13         3.0      sedang
14         4.0       besar

#### Data Petal Length

In [ ]:
Petal_Length_Binning = pd.cut(df2['petal_length'],len(labels), True, labels)
Labelled_Petal_Length_Binning = Petal_Length_Binning.value_counts()
NoLabelled_Petal_Length_Binning = pd.cut(df2['petal_length'],len(labels)).value_counts()
# IntervalBinning = pd.cut()

In [ ]:
Labelled_Petal_Length_Binning

sedang    54
kecil     50
besar     46
Name: petal_length, dtype: int64

In [ ]:
pd.concat((df2['petal_length'],Petal_Length_Binning),axis=1)

    petal_length petal_length
0            1.4        kecil
1            1.4        kecil
2            1.3        kecil
3            1.5        kecil
4            1.4        kecil
..           ...          ...
145          5.2        besar
146          5.0        besar
147          5.2        besar
148          5.4        besar
149          5.1        besar

[150 rows x 2 columns]

#### Petal Width

In [ ]:
Petal_Width_Binning = pd.cut(df2['petal_width'],len(labels), True, labels)
Labelled_Petal_Width_Binning = Petal_Width_Binning.value_counts()
NoLabelled_Petal_Width_Binning = pd.cut(df2['petal_width'],len(labels)).value_counts()
# IntervalBinning = pd.cut()

In [ ]:
Labelled_Petal_Width_Binning

sedang    54
kecil     50
besar     46
Name: petal_width, dtype: int64

In [ ]:
pd.concat((df2['petal_width'],Petal_Width_Binning),axis=1)

    petal_width petal_width
0           0.2       kecil
1           0.2       kecil
2           0.2       kecil
3           0.2       kecil
4           0.2       kecil
..          ...         ...
145         2.3       besar
146         1.9       besar
147         2.0       besar
148         2.3       besar
149         1.8       besar

[150 rows x 2 columns]

### Data Equal Frequency

#### Data Sepal Length

In [ ]:
Qcut_Sepal_Length_Binning = pd.qcut(df2['sepal_length'],len(labels), labels)
Labelled_Qcut_Sepal_Length_Binning = Qcut_Sepal_Length_Binning.value_counts()
NoLabelled_Qcut_Sepal_Length_Binning = pd.qcut(df2['sepal_length'],len(labels)).value_counts()
# IntervalBinning = pd.qcut()

In [ ]:
Labelled_Qcut_Sepal_Length_Binning

sedang    56
kecil     52
besar     42
Name: sepal_length, dtype: int64

In [ ]:
pd.concat((df2['sepal_length'],Qcut_Sepal_Length_Binning),axis=1)

    sepal_length sepal_length
0            5.1        kecil
1            4.9        kecil
2            4.7        kecil
3            4.6        kecil
4            5.0        kecil
..           ...          ...
145          6.7        besar
146          6.3       sedang
147          6.5        besar
148          6.2       sedang
149          5.9       sedang

[150 rows x 2 columns]

#### Data Sepal Width

In [ ]:
Qcut_Sepal_Width_Binning = pd.qcut(df2['sepal_width'],len(labels), labels)
Labelled_Qcut_Sepal_Width_Binning = Qcut_Sepal_Width_Binning.value_counts()
NoLabelled_Qcut_Sepal_Width_Binning = pd.qcut(df2['sepal_width'],len(labels)).value_counts()
# IntervalBinning = pd.qcut()

In [ ]:
Labelled_Qcut_Sepal_Width_Binning

kecil     57
sedang    51
besar     42
Name: sepal_width, dtype: int64

In [ ]:
pd.concat((df2['sepal_width'],Qcut_Sepal_Width_Binning),axis=1)

    sepal_width sepal_width
0           3.5       besar
1           3.0      sedang
2           3.2      sedang
3           3.1      sedang
4           3.6       besar
..          ...         ...
145         3.0      sedang
146         2.5       kecil
147         3.0      sedang
148         3.4       besar
149         3.0      sedang

[150 rows x 2 columns]

#### Data Petal Length

In [ ]:
Qcut_Petal_Length_Binning = pd.qcut(df2['petal_length'],len(labels), labels)
Labelled_Qcut_Petal_Length_Binning = Qcut_Petal_Length_Binning.value_counts()
NoLabelled_Qcut_Petal_Length_Binning = pd.qcut(df2['petal_length'],len(labels)).value_counts()
# IntervalBinning = pd.qcut()

In [ ]:
Labelled_Qcut_Petal_Length_Binning

sedang    54
kecil     50
besar     46
Name: petal_length, dtype: int64

In [ ]:
pd.concat((df2['petal_length'],Qcut_Petal_Length_Binning),axis=1)

    petal_length petal_length
0            1.4        kecil
1            1.4        kecil
2            1.3        kecil
3            1.5        kecil
4            1.4        kecil
..           ...          ...
145          5.2        besar
146          5.0        besar
147          5.2        besar
148          5.4        besar
149          5.1        besar

[150 rows x 2 columns]

#### Data Petal Width

In [ ]:
Qcut_Petal_Width_Binning = pd.qcut(df2['petal_width'],len(labels), labels)
Labelled_Qcut_Petal_Width_Binning = Qcut_Petal_Width_Binning.value_counts()
NoLabelled_Qcut_Petal_Width_Binning = pd.qcut(df2['petal_width'],len(labels)).value_counts()
# IntervalBinning = pd.qcut()

In [ ]:
Labelled_Qcut_Petal_Width_Binning

sedang    52
kecil     50
besar     48
Name: petal_width, dtype: int64

In [ ]:
pd.concat((df2['petal_width'],Qcut_Petal_Width_Binning),axis=1)

    petal_width petal_width
0           0.2       kecil
1           0.2       kecil
2           0.2       kecil
3           0.2       kecil
4           0.2       kecil
..          ...         ...
145         2.3       besar
146         1.9       besar
147         2.0       besar
148         2.3       besar
149         1.8       besar

[150 rows x 2 columns]

## 2. Lakukan proses diskritisasi dengan basis entropy
>*Entropy adalah*

>*   Rumus Entropy :



$$Entropy (D_{1}) = -\sum_{i=1}^{m} Pi \log_{2} Pi$$

>*   Rumus Gain :



$$Gain(E_{new}) = E_{initial} - E_{new}$$
>*   Rumus Info :



$$Info_{A}(D) = \frac{|D_{_{1}}|}{|D|} Entropy(D_{1}) + \frac{|D_{2}|}{|D|} Entropy(D_{2})$$

Membuat sample data untuk di analisis

In [ ]:
sample=df2[['sepal_length']]
sample.describe()

       sepal_length
count    150.000000
mean       5.843333
std        0.828066
min        4.300000
25%        5.100000
50%        5.800000
75%        6.400000
max        7.900000

### Membuat Kategori

In [ ]:

np.random.seed(0)
sample["kategori"] = np.where(np.random.choice(2,sample.shape[0]) < 1,"A","B")
sample

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

     sepal_length kategori
0             5.1        A
1             4.9        B
2             4.7        B
3             4.6        A
4             5.0        B
..            ...      ...
145           6.7        A
146           6.3        B
147           6.5        B
148           6.2        B
149           5.9        B

[150 rows x 2 columns]

### Membuat fungsi GetOverollCategory (keseluruhan) yang digunakan untuk menghitung data keseluruhan yang nantinya digunakan untuk menghitung entropy

In [ ]:
def GetOverollCategory(col):
  group = sample.loc[:, :].groupby("kategori").count()
  a = group.loc['A', col]
  b = group.loc["B", col]
  return (a,b,a+b)

### Memasukan fungsi splitter yang digunakan untuk membuat split antara value yang telah ditentukan lalu mengembalikan data yang telah dipisahkan

In [ ]:
def splitter(value, col):
  #get data less and greater from value
  less = sample[sample[col] <= value]
  greater = sample[sample[col] > value]

  #calculate into category for each data
  less_group = less.loc[:, :].groupby("kategori").count()
  greater_group = greater.loc[:, :].groupby("kategori").count()

  #get value based on category
  less_category_A = less_group.loc['A',col]
  less_category_B = less_group.loc["B",col]
  greater_category_A = greater_group.loc['A',col]
  greater_category_B = greater_group.loc["B",col]

  return (
      [less_category_A, less_category_B, less_category_A + less_category_B],
      [greater_category_A, greater_category_B, greater_category_A + greater_category_B]
  )

### Membuat fungsi entropy untuk melakukan perhitungan entropy (menggunakan rumus entropy)

In [ ]:
def entropy (d):
  r1 = (d[0] / d[2]) * np.log2(d[0] / d[2])
  r2 = (d[1] / d[2]) * np.log2(d[1] / d[2])
  return np.sum([r1, r2]) * -1

### Membuat fungsi info

In [ ]:
def info(d):
  r1 = (d[0][2] / sample.shape[0]) * entropy(d[0])
  r2 = (d[1][2] / sample.shape[0]) * entropy(d[1])
  return r1 + r2

### Membuat fungsi gain

In [ ]:
def gain(Einitial, Enew):
  return Einitial - Enew

### Membuat Dinitial

In [ ]:
get_overoll = GetOverollCategory("sepal_length")
entropy_data = entropy(get_overoll)
print(get_overoll)
print(entropy_data)

(68, 82, 150)
0.993707106604508

### Melakukan beberapa split

In [ ]:
split1 = splitter(5, "sepal_length")
info_split1 = info(split1)
gain(entropy_data, info_split1)

0.016048641191889423

In [ ]:
split2 = splitter(6.5, "sepal_length")
info_split2 = info(split2)
gain(entropy_data, info_split2)

0.00012921701793400242

In [ ]:
split3 = splitter(7, "sepal_length")
info_split3 = info(split3)
gain(entropy_data, info_split3)

0.0005490214732508658